### ISSUE TITLE
Circular dependency detected

### ISSUE THREAD

**Issue by shankardevy** [james2m/seedbank#43]
`Circular dependency detected: TOP => db:seed:provider => db:seed:common => db:seed:provider`

I have only file called provider.seeds.rb in my 'db/seeds' directory.

Calling `./bin/rake db:seed:provider` gives me this error.

I am using Rails 4.2.beta1, btw.

**Comment by jsmecham** [comment]
I'm seeing this problem, as well.

**Comment by Tronix117** [comment]
Same here, except I also have a subfolder with same name containing YML files.
And I am on Rails 3.2.21

    ** Invoke db:seed:scope (first_time)
    ** Invoke db:abort_if_pending_migrations (first_time)
    ** Invoke environment (first_time)
    ** Execute environment
    ** Invoke db:load_config (first_time)
    ** Execute db:load_config
    ** Execute db:abort_if_pending_migrations
    ** Invoke db:seed:common (first_time)
    ** Invoke db:seed:original (first_time)
    ** Invoke db:abort_if_pending_migrations
    ** Execute db:seed:original
    rake aborted!
    Circular dependency detected: TOP => db:seed:scope => db:seed:common => db:seed:scope
    ~/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/invocation_chain.rb:16:in `append'
    ~/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/invocation_chain.rb:28:in `append'

**Comment by james2m** [comment]
Have you tried 0.4.pre?

**Comment by jsmecham** [comment]
I saw this problem as well, however, my seeder was named "resources". Renaming it to "resources_" fixed the issue, but I didn't dive any deeper. Seems like reserved words are causing a problem somewhere.

**Comment by james2m** [comment]
This is certainly in the cases I've seen caused by having duplicate task names in the db:common and a sub directory. @Tronix117 case in point. The short term answer is don't do this;

```bash
db/seeds.rb
db/seeds/duplicate.seeds.rb
db/seeds/duplicate/other.seeds.rb
```

As you will end up with the 'environment' task db:seed:duplicate (created from the directory db/seeds/duplicate) dependent on db:seed:common which will have a dependency on the common seed db:seed:duplicate (created from the seed file db/seeds/duplicate.seeds.rb).

I'm thinking about forcing collision detection when creating the tasks, but it's quite a re-write so for the time being, avoid directory names with the same name as a seed file.

**Comment by JimW** [comment]
I followed the "Defining and using methods" instructions exactly and also got:
Circular dependency detected: TOP => db:seed => db:seed:common => db:seed:common

Fixed it by changing the name of the common seed from common.seed.rb to default.seed.rb

**Comment by james2m** [comment]
@JimW what's the chances you've a db/seeds/common folder or a common.seeds.rb?

**Comment by JimW** [comment]
Yes, renaming common.seed.rb to default.seed.rb fixes things. Thanks

**Comment by bbugh** [comment]
The problem seems to be `?.seeds.rb` where `?` is also the name of a subfolder. I made a file `db/seeds/report_templates.seeds.rb`. There's also a subfolder `db/seeds/report_templates/*` that contain the template files. If I try to run these seeds, I get the circular dependency detected issue. If I rename either the `report_templates.seeds.rb` file or `db/seeds/report_templates/` it works fine.

This is on `0.5.0pre`

**Comment by james2m** [comment]
This is more of a documentarian issue I think. As a seed for each subdirectory isn’t going away. It’s possible to maybe detect the duplicate and not allow it with a warning message. What do you think?
